name: Build and Release React Native APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          yarn install

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Get current time
        id: get_time
        run: echo "CURRENT_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Set up environment variables
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICE_BASE64 }}
        run: |
          echo "$GOOGLE_SERVICES_JSON" | base64 -d > ./android/app/google-services.json

      - name: Install Android dependencies
        uses: android-actions/setup-android@v2
        with:
          distribution: 'latest'

      - name: Generate local.properties file
        run: |
          cd android
          echo "sdk.dir=${ANDROID_SDK_ROOT}" > local.properties
          cd ..

      - name: Make Gradle executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease -PbuildType=Release
          cd ..

      - name: Rename APK with version
        run: mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/${{ secrets.APP_NAME }}_${{ env.VERSION }}.apk

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/${{ secrets.APP_NAME }}_${{ env.VERSION }}.apk